/**
 * Copy for the AIOps services page (/aiops-services.html) and the home-page AIOps section.
 * Source: the Enterprise AIOps Portfolio (8 tracks, 40 services). These are service offerings
 * and example scenarios, not client results: no client names, no metrics (task FM-701).
 * Icon keys are files in /public/images/icons/; images are generated by tools/images/scenes/aiops.mjs.
 */
import type { Card } from "./content";

export type AiopsTrack = {
  id: string; // anchor: #track-<id>
  icon: string;
  image: string;
  imageAlt: string;
  name: string;
  tagline: string;
  services: { name: string; text: string }[];
  scenario: string;
};

export const aiops = {
  slug: "aiops-services",
  navLabel: "AIOps Services",
  title: "AIOps Services: SRE, Security, GRC, Network, Cloud, FinOps & MLOps | FluxMigrate",
  description:
    "AIOps services from FluxMigrate: incident intelligence, self-healing, security correlation, continuous compliance, network diagnosis, cloud operations, FinOps, DevSecOps and MLOps/LLMOps, with policy-controlled automation and audit evidence.",
  badge: "AIOps services",
  h1: "AIOps that **detects, decides and acts** under your control",
  subtitle:
    "FluxMigrate designs and builds AIOps across eight operational domains. Signals become decisions, decisions pass policy, approved actions run from validated runbooks, and every outcome is verified and recorded.",
  cta: { label: "Talk to an AIOps Specialist", href: "/contact.html" },
  heroImage: "/images/heroes/aiops-overview.webp",
  heroAlt:
    "Illustrative view: eight AIOps tracks (SRE, Cybersecurity, GRC, Network, CloudOps, FinOps, DevSecOps, MLOps and LLMOps) around one platform, above the closed loop from signal to evidence",
  tracksTitle: "Eight AIOps tracks, **forty services**",
  tracksText:
    "Each track is a set of five services. Take one on its own, or combine tracks so telemetry, policy and runbooks are shared.",
  home: {
    badge: "AIOps services",
    title: "AIOps for operations, security and AI systems, **with guardrails.**",
    text: "Eight tracks that turn signals into governed action: detect, decide, check policy, act, verify and keep the evidence.",
    button: { label: "Explore AIOps Services", href: "/aiops-services.html" },
  },
  loop: {
    title: "One closed loop **behind every service**",
    intro: "Whatever the domain, the same chain runs from first signal to final evidence.",
    items: [
      { title: "Signal", text: "Collect and normalize telemetry, events and findings from the systems you already run." },
      { title: "Decision", text: "Detect, correlate and score. Start with rules and statistics; add machine learning where it earns its place." },
      { title: "Policy", text: "Check risk, ownership and approval rules before anything changes." },
      { title: "Approval", text: "A person approves disruptive or high-risk actions by default." },
      { title: "Action", text: "Run a validated, allowlisted runbook under a least-privilege identity." },
      { title: "Verify", text: "Check service health after the action and roll back if it did not help." },
      { title: "Evidence", text: "Keep the decision, approval, action and result as an audit trail." },
      { title: "Feedback", text: "Record overrides and outcomes so scoring improves and stays explainable." },
    ],
  },
  guardrailsTitle: "Automation with **guardrails, not blind trust**",
  guardrails: [
    { icon: "guard-allowlist", title: "Allowlisted actions only", text: "AI output never goes straight to a shell, cloud API or cluster. It selects from validated runbooks." },
    { icon: "guard-approval", title: "Approval for high-risk change", text: "Disruptive actions wait for a person. Low-risk, reversible steps can run on their own once you agree the rule." },
    { icon: "guard-verify", title: "Verified outcomes", text: "Every action is followed by a health check, with rollback or compensation when the check fails." },
    { icon: "guard-audit", title: "Complete audit history", text: "Signals, scores, model or rule versions, approvals and results are retained and reviewable." },
  ] as Card[],
  deliverTitle: "From a safe baseline **to your environment**",
  deliverIntro:
    "We build locally with realistic synthetic data first, then extend to your private cloud and to AWS, Azure or GCP.",
  deliver: [
    { icon: "deliver-baseline", title: "Deterministic baseline", text: "Rules and statistics first, so every decision can be explained before machine learning is added." },
    { icon: "deliver-lab", title: "Prove it in a lab", text: "Healthy, faulty, false-positive, policy-blocked and failed-automation cases are exercised before production." },
    { icon: "deliver-extend", title: "Extend to your estate", text: "Adapters for your clouds, clusters, networks and tools, using Terraform, Ansible and Helm." },
    { icon: "deliver-handover", title: "Hand over with runbooks", text: "Dashboards, runbooks, tests and a demo script your team can operate and extend." },
  ] as Card[],
  scenarioLabel: "Example scenario",
  closing: {
    title: "Which AIOps track fits **your environment?**",
    text: "Tell us what you run and where operations hurt most. We will suggest where to start.",
    cta: { label: "Talk to an AIOps Specialist", href: "/contact.html" },
  },
  tracks: [
    {
      id: "sre", icon: "aiops-sre", image: "/images/heroes/aiops-sre.webp",
      imageAlt: "Illustrative view: alerts from many systems collapse into one incident with a probable cause, an approved rollback and a verified service-level recovery",
      name: "SRE AIOps",
      tagline: "Reliability, SLOs, incident intelligence, predictive operations and self-healing across hybrid environments.",
      services: [
        { name: "Autonomous SRE & AIOps Command Center", text: "Unify multi-site and cloud telemetry, correlate incidents, find probable root cause and coordinate safe remediation." },
        { name: "AI Self-Healing Infrastructure", text: "Detect recurring failures and run policy-controlled remediation with verification." },
        { name: "Predictive SRE: Failure & Capacity Forecasting", text: "Forecast capacity exhaustion and SLO risk before static thresholds are breached." },
        { name: "ChangeGuard: Change Risk & Deployment Reliability", text: "Score code, IaC and Kubernetes changes, control progressive delivery and roll back unhealthy releases." },
        { name: "Resilience, DR & Chaos Engineering", text: "Prove DR readiness, backup restorability, failover and RTO/RPO through safe experiments." },
      ],
      scenario: "A faulty release is injected. Several symptoms collapse into one incident, a rollback is approved and SLO recovery is verified.",
    },
    {
      id: "security", icon: "aiops-security", image: "/images/heroes/aiops-security.webp",
      imageAlt: "Illustrative view: raw events from SIEM, endpoint, cloud, firewall and identity sources become one prioritized incident with a guided response",
      name: "Cybersecurity AIOps",
      tagline: "AI-assisted threat detection, security-event correlation, behavioral analytics and governed response.",
      services: [
        { name: "SOC Threat Correlation & Incident Response", text: "Turn SIEM, EDR, cloud, firewall and identity alerts into prioritized incidents with guided response." },
        { name: "Vulnerability Prioritization & Remediation", text: "Rank vulnerabilities by exploitability, exposure, runtime context and asset criticality." },
        { name: "Identity & UEBA Detection and Response", text: "Spot suspicious user and service-account behavior against learned login and privilege baselines." },
        { name: "Cloud & Kubernetes Threat Containment", text: "Detect runtime and control-plane threats and apply tightly scoped containment." },
        { name: "Phishing, Malware & Security Triage", text: "Automate safe enrichment, classification and case creation for suspicious messages, files and URLs." },
      ],
      scenario: "Credential abuse followed by lateral movement is simulated. Raw events collapse into one incident with a guided response.",
    },
    {
      id: "grc", icon: "aiops-grc", image: "/images/heroes/aiops-grc.webp",
      imageAlt: "Illustrative view: a control coverage matrix, a risk heatmap and an automated audit evidence package",
      name: "GRC AIOps",
      tagline: "Continuous compliance, automated evidence, risk analytics and policy-as-code across hybrid infrastructure.",
      services: [
        { name: "Continuous Compliance & Auto-Remediation", text: "Test cloud, Kubernetes, Linux and IaC against mapped controls and fix approved violations." },
        { name: "EvidenceOps: Audit Evidence & Control Testing", text: "Replace manual evidence collection with scheduled collectors and automated control tests." },
        { name: "Risk Register & Control Gap Prediction", text: "Update operational risk from incidents, vulnerabilities, failed controls and asset criticality." },
        { name: "Policy-as-Code & Drift Management", text: "Turn governance requirements into executable policy for CI/CD, cloud and Kubernetes." },
        { name: "Third-Party & Vendor Risk", text: "Track vendor risk using attestations, SLA incidents, questionnaires and approved external inputs." },
      ],
      scenario: "A known violation is introduced, mapped to controls and remediated, with before and after evidence.",
    },
    {
      id: "network", icon: "aiops-network", image: "/images/heroes/aiops-network.webp",
      imageAlt: "Illustrative view: a network topology where one failed link is ranked as root cause, with a path-health forecast and suppressed alert noise",
      name: "Network AIOps",
      tagline: "Topology-aware observability, prediction, root-cause analysis and safe automation across WAN, cloud and Kubernetes networking.",
      services: [
        { name: "Global Network AIOps Command Center", text: "Unify health, topology, incidents and automation for enterprise, cloud and Kubernetes networks." },
        { name: "Predictive WAN / SD-WAN & Path Optimization", text: "Forecast path degradation from latency, loss, jitter and utilization and recommend safe path changes." },
        { name: "Network Root Cause Analysis & Self-Healing", text: "Suppress downstream symptoms, rank the probable root cause and run approved repair workflows." },
        { name: "Network Security Policy Drift", text: "Detect risky firewall, security-group and network-policy drift and conflicting rules." },
        { name: "Kubernetes & Service Mesh Network AIOps", text: "Correlate CNI, DNS, ingress, NetworkPolicy and mesh signals to diagnose cluster networking failures." },
      ],
      scenario: "One upstream failure raises many alerts. The actual root cause is identified and the downstream symptoms are suppressed.",
    },
    {
      id: "cloud", icon: "aiops-cloud", image: "/images/heroes/aiops-cloud.webp",
      imageAlt: "Illustrative view: AWS, Azure, Google Cloud and private cloud under one operations layer, with drift reconciliation, workload placement and outage blast radius",
      name: "CloudOps AIOps",
      tagline: "Hybrid and multi-cloud inventory, health analytics, drift intelligence, workload placement and governed remediation.",
      services: [
        { name: "Hybrid & Multi-Cloud Operations Control Plane", text: "One operations layer for AWS, Azure, GCP and private-cloud inventory, health, incidents, changes and automation." },
        { name: "Cloud Resource Health & Auto-Remediation", text: "Detect unhealthy cloud resources and recover them under policy control." },
        { name: "Configuration Drift & Governance Remediation", text: "Compare cloud state with desired IaC and policy and safely reconcile drift." },
        { name: "Multi-Cloud Capacity & Workload Placement", text: "Recommend placement from capacity, latency, availability, policy and cost inputs, with reasons." },
        { name: "Service Dependency & Outage Impact", text: "Map applications to cloud dependencies, correlate provider events and estimate blast radius." },
      ],
      scenario: "Console drift is created, then the intended state is restored through Git and IaC.",
    },
    {
      id: "finops", icon: "aiops-finops", image: "/images/heroes/aiops-finops.webp",
      imageAlt: "Illustrative view: a spend anomaly with a guardrail, Kubernetes rightsizing, showback allocation, commitment scenarios and a cost-performance comparison",
      name: "FinOps AIOps",
      tagline: "Cost anomaly detection, rightsizing, forecasting and allocation that respect reliability targets.",
      services: [
        { name: "Cost Anomaly Detection & Auto-Guardrails", text: "Detect abnormal spend early and trigger governed cost-control workflows." },
        { name: "Kubernetes Rightsizing & Efficiency", text: "Tune CPU and memory requests, limits and replicas from real utilization while protecting SLOs." },
        { name: "Commitment & Savings Forecasting", text: "Forecast stable usage and model commitment scenarios with risk buffers." },
        { name: "Showback, Chargeback & Unit Economics", text: "Allocate shared cost and calculate cost per service, customer, transaction or team." },
        { name: "GreenOps: Cost, Carbon & Performance", text: "Balance cost, performance, utilization and sustainability signals within SLO limits." },
      ],
      scenario: "A synthetic spend spike is injected. It is detected, attributed and met with a low-risk guardrail.",
    },
    {
      id: "devsecops", icon: "aiops-devsecops", image: "/images/heroes/aiops-devsecops.webp",
      imageAlt: "Illustrative view: a release pipeline held at an unsigned artifact, scanner findings ranked into a short backlog, a supply-chain tree and secret and access fixes",
      name: "DevSecOps AIOps",
      tagline: "Software-delivery reliability, AppSec prioritization, supply-chain protection and secure release automation.",
      services: [
        { name: "CI/CD Pipeline Reliability & Root Cause", text: "Classify pipeline failures, spot flaky and transient issues and recommend safe recovery." },
        { name: "Application Security Risk Prioritization", text: "Deduplicate and rank SAST, DAST, dependency, container and IaC findings by exploitability and context." },
        { name: "Software Supply Chain Security", text: "Track SBOMs, provenance, artifact signatures, dependencies and build integrity." },
        { name: "Secure Release Orchestration", text: "Combine tests, security, IaC policy, live SLO health and change risk into one governed release gate." },
        { name: "Secrets, IAM & Access Misconfiguration Prevention", text: "Find exposed secrets and excessive permissions across code, CI/CD, Kubernetes and cloud configuration." },
      ],
      scenario: "A healthy release and a risky one are compared and receive different promotion outcomes.",
    },
    {
      id: "mlops", icon: "aiops-mlops", image: "/images/heroes/aiops-mlops.webp",
      imageAlt: "Illustrative view: an AI agent trace where a production change is denied by policy, model drift with a promotion gate, and inference capacity scaling ahead of demand",
      name: "MLOps / LLMOps AIOps",
      tagline: "Reliability, observability, governance and capacity for ML models, LLM applications and AI agents.",
      services: [
        { name: "Model Reliability & Production Operations", text: "Operate model endpoints with SLOs, quality signals, version context and safe rollback." },
        { name: "LLM & AI Agent Observability and Guardrails", text: "Trace prompts, tokens, tool calls and agent steps while enforcing operational policy." },
        { name: "GPU & Inference Capacity Optimization", text: "Forecast inference demand and tune scaling, batching and placement while protecting latency." },
        { name: "Model & Data Drift with Automated Retraining", text: "Detect feature, prediction and performance drift and trigger validation and retraining pipelines." },
        { name: "AI Governance, Prompt Security & Model Risk", text: "Monitor model, prompt and tool policy compliance, data handling and AI-system risk." },
      ],
      scenario: "An agent attempts a disallowed action. Policy intercepts it and the trace shows exactly why.",
    },
  ] as AiopsTrack[],
};
