/**
 * All page copy for fluxmigrate.com, ported unchanged from the previous static site.
 * `**bold**` inside a title is rendered in the theme's accent colour.
 * `icon` values are keys of /public/images/icons/<key>.svg (generated by tools/images).
 */

export type Cta = { label: string; href: string };

export type Card = { icon: string; title: string; text: string };
export type Group = { icon: string; title: string; list: string[] };

export type Block =
  | { type: "cards"; title: string; intro?: string; columns?: 2 | 3 | 4; items: Card[] }
  | { type: "groups"; title: string; intro?: string; columns?: 2 | 3 | 4; items: Group[] }
  | { type: "steps"; title: string; intro?: string; items: { title: string; text: string }[] }
  | { type: "chips"; title: string; intro?: string; items: string[]; footnote?: string }
  | { type: "tabs"; title: string; intro?: string; tabs: { id: string; label: string; icon: string; items: string[] }[] };

export type PageContent = {
  slug: string; // served as /<slug>.html
  navLabel: string;
  title: string; // <title>
  description: string;
  h1: string;
  subtitle: string;
  cta?: Cta;
  heroImage: string; // /images/heroes/<name>.webp
  heroAlt: string;
  schema?: { type: string; name: string };
  blocks: Block[];
  closing?: { title: string; text: string; cta: Cta };
};

/* ------------------------------------------------------------------ shared */

export const paths: { tag: string; title: string; label: string; href: string }[] = [
  { tag: "Need a project?", title: "Plan a Cloud / Infrastructure Project", label: "Start a project", href: "/contact.html" },
  { tag: "Need engineers?", title: "Request DevOps / Cloud / SRE Engineers", label: "Explore staff augmentation", href: "/staff-augmentation.html" },
  { tag: "Need help designing your environment?", title: "Book a Technical Discovery Call", label: "Book a call", href: "/contact.html" },
];

/* -------------------------------------------------------------------- home */

export const home = {
  title: "FluxMigrate | Cloud Infrastructure, DevOps & Reliability Engineering",
  description:
    "FluxMigrate helps organizations design, migrate, automate and operate modern cloud and hybrid infrastructure, and provides Cloud, DevOps, Platform and SRE engineers to extend your team.",
  badge: "Cloud · DevOps · SRE · Engineering",
  h1: "Modern infrastructure, **engineered for change.**",
  lede: "FluxMigrate designs, migrates and operates secure cloud and hybrid platforms across AWS, Azure, GCP, Kubernetes, OpenShift, VMware, OpenStack and enterprise Linux.",
  body: "Bring us a defined transformation or embed our Cloud, DevOps and SRE specialists directly into your engineering team.",
  primary: { label: "Talk to an Engineering Specialist", href: "/contact.html" },
  secondary: { label: "Explore Our Services", href: "/cloud-migration.html" },
  heroImage: "/images/heroes/platform-overview.webp",
  heroAlt:
    "Illustrative platform view: a migration from a source estate onto a modern platform, with delivery pipelines and service-level monitoring",
  capabilities: {
    title: "Engineering across the platforms **your environment already runs on**",
    text: "From public cloud to private virtualization, automation and observability.",
    items: ["AWS", "Azure", "Google Cloud", "Kubernetes", "OpenShift", "VMware", "OpenStack", "Linux"],
  },
  lifecycle: {
    title: "Engineering expertise for every **stage of your infrastructure lifecycle**",
    items: [
      { icon: "design", title: "Design", list: ["Cloud & Hybrid Architecture", "Kubernetes Architecture", "HA & DR"] },
      { icon: "migrate", title: "Migrate", list: ["Cloud & Data Center Migration", "VMware Modernization", "Legacy Modernization"] },
      { icon: "automate", title: "Automate", list: ["DevOps & IaC", "CI/CD", "Terraform / Ansible"] },
      { icon: "operate", title: "Operate", list: ["SRE & Managed Operations", "Monitoring", "Incident Response"] },
    ] as Group[],
  },
  evidence: {
    badge: "Operational evidence",
    title: "Working systems. Transferable knowledge. **No black box.**",
    text: "Every engagement is structured around tangible engineering outputs your team can operate, review and extend.",
    items: [
      { icon: "decisions", title: "Decisions documented", text: "Architecture records, dependency maps and migration plans make technical choices visible." },
      { icon: "reproducible", title: "Infrastructure reproducible", text: "Version-controlled automation, pipelines and environment definitions reduce manual drift." },
      { icon: "opsready", title: "Operations ready", text: "Runbooks, observability, SLOs and knowledge transfer support long-term ownership." },
    ] as Card[],
  },
  services: {
    badge: "What we do",
    title: "Cloud, security and platform services, **end to end.**",
    text: "Each service below is delivered by senior engineers — as a scoped project or as capacity embedded in your team. Open a service for details, or talk to a specialist about any of them.",
    items: [
      { id: "service-devsecops", icon: "devsecops", title: "DevSecOps", text: "Security scanning, policy-as-code and compliance gates built into the pipeline, not bolted on after release.", href: "/contact.html", label: "Talk to a specialist" },
      { id: "service-devops", icon: "devops", title: "DevOps & Platform", text: "CI/CD, Infrastructure as Code and platform engineering that make delivery repeatable.", href: "/devops-platform-engineering.html", label: "Discover more" },
      { id: "service-cloud", icon: "cloud", title: "Cloud & Migration", text: "Architecture, migration and modernization across AWS, Azure, GCP, VMware and OpenStack.", href: "/cloud-migration.html", label: "Discover more" },
      { id: "service-professional", icon: "staff", title: "Staff Augmentation", text: "Senior Cloud, DevOps and SRE engineers embedded in your team, plus scoped architecture and consultancy engagements.", href: "/staff-augmentation.html", label: "Discover more" },
      { id: "service-managed", icon: "sre", title: "SRE & Reliability", text: "Observability, incident response and round-the-clock operations for production systems that can't go dark.", href: "/sre-reliability-engineering.html", label: "Discover more" },
      { id: "service-kubernetes", icon: "kubernetes", title: "Kubernetes Services", text: "Cluster architecture, GitOps delivery and day-2 operations for Kubernetes and OpenShift at production scale.", href: "/contact.html", label: "Talk to a specialist" },
      { id: "service-finops", icon: "finops", title: "FinOps Consulting", text: "Cost visibility, rightsizing and commitment planning that turn cloud spend into a governed, forecastable line item.", href: "/contact.html", label: "Talk to a specialist" },
      { id: "service-well-architected", icon: "wellarch", title: "Well-Architected Review", text: "A structured audit against the AWS and Azure Well-Architected pillars, with a prioritized remediation roadmap.", href: "/contact.html", label: "Talk to a specialist" },
      { id: "service-vmware", icon: "vmware", title: "VMware Modernization", text: "A structured exit path off VMware — target platform selection, workload migration and cutover, without unplanned downtime.", href: "/vmware-modernization.html", label: "Discover more" },
    ],
  },
  cta: {
    badge: "Engineering capacity",
    title: "Need additional **engineering capacity?**",
    text: "Add experienced Cloud, DevOps, Platform or SRE engineers to your team without the long hiring cycle.",
    button: { label: "Request Engineers", href: "/staff-augmentation.html" },
  },
};

/* ------------------------------------------------------------ service pages */

export const pages: PageContent[] = [
  {
    slug: "cloud-migration",
    navLabel: "Cloud & Migration",
    title: "Cloud Migration & Modernization | FluxMigrate",
    description:
      "Structured, low-risk cloud and data-center migration across AWS, Azure, GCP and VMware, from discovery through optimization.",
    h1: "Migrate and modernize infrastructure **with a proven methodology**",
    subtitle:
      "FluxMigrate plans and executes cloud and data-center migrations with a structured, low-risk approach — from initial discovery through post-migration optimization.",
    cta: { label: "Plan a Cloud / Infrastructure Project", href: "/contact.html" },
    heroImage: "/images/heroes/cloud-migration.webp",
    heroAlt: "Illustrative diagram: workloads moving from a source estate to a modern cloud platform",
    schema: { type: "Service", name: "Cloud Migration and Modernization" },
    blocks: [
      {
        type: "cards",
        title: "Four migration **scenarios**",
        columns: 4,
        items: [
          { icon: "dc-cloud", title: "Data Center → Cloud", text: "AWS / Azure / GCP" },
          { icon: "cloud-cloud", title: "Cloud → Cloud", text: "AWS ↔ Azure ↔ GCP" },
          { icon: "vmware-alt", title: "VMware → Alternatives", text: "VMware modernization and migration" },
          { icon: "legacy-modern", title: "Legacy → Modern Platform", text: "VMs → containers → Kubernetes/OpenShift" },
        ],
      },
      {
        type: "steps",
        title: "Our **methodology**",
        items: [
          { title: "Discover", text: "Understand current environment, workloads and business drivers." },
          { title: "Assess", text: "Evaluate dependencies, risk and migration readiness." },
          { title: "Design", text: "Architect the target environment and migration approach." },
          { title: "Build", text: "Stand up target infrastructure and automation." },
          { title: "Migrate", text: "Execute the move in planned, low-risk phases." },
          { title: "Validate", text: "Confirm functionality, performance and data integrity." },
          { title: "Optimize", text: "Tune cost, performance and security post-migration." },
          { title: "Operate", text: "Transition to ongoing operations and reliability engineering." },
        ],
      },
    ],
  },
  {
    slug: "devops-platform-engineering",
    navLabel: "DevOps & Platform",
    title: "DevOps & Platform Engineering | FluxMigrate",
    description:
      "CI/CD, Infrastructure as Code and platform engineering that make software delivery faster and more reliable.",
    h1: "Build a repeatable **software delivery and infrastructure platform**",
    subtitle:
      "FluxMigrate designs and implements CI/CD pipelines, Infrastructure as Code and platform engineering practices that let development teams ship faster without sacrificing stability or security.",
    cta: { label: "Modernize Your DevOps Platform", href: "/contact.html" },
    heroImage: "/images/heroes/devops-platform.webp",
    heroAlt: "Illustrative diagram: an automated delivery pipeline from commit to production",
    schema: { type: "Service", name: "DevOps and Platform Engineering" },
    blocks: [
      {
        type: "groups",
        title: "What we **build**",
        columns: 3,
        items: [
          { icon: "cicd", title: "CI/CD", list: ["Jenkins", "Azure DevOps", "Git", "Release automation"] },
          { icon: "iac", title: "Infrastructure as Code", list: ["Terraform", "Ansible", "Configuration management"] },
          { icon: "platform", title: "Platform Engineering", list: ["Docker & Kubernetes", "OpenShift", "Developer self-service"] },
        ],
      },
    ],
  },
  {
    slug: "sre-reliability-engineering",
    navLabel: "SRE & Reliability",
    title: "SRE & Reliability Engineering | FluxMigrate",
    description:
      "Improve availability, observability and operational resilience with FluxMigrate's Site Reliability Engineering practices.",
    h1: "Make reliability **an engineering discipline**",
    subtitle:
      "FluxMigrate helps organizations improve availability, observability and operational resilience through Site Reliability Engineering practices and automation.",
    cta: { label: "Talk to an SRE Specialist", href: "/contact.html" },
    heroImage: "/images/heroes/sre-reliability.webp",
    heroAlt: "Illustrative diagram: a service level held through an incident and recovery",
    schema: { type: "Service", name: "Site Reliability Engineering" },
    blocks: [
      {
        type: "groups",
        title: "Reliability, **from design to operations**",
        columns: 4,
        items: [
          { icon: "reliability", title: "Reliability Engineering", list: ["SLI/SLO design", "Availability engineering", "Capacity planning", "Failure analysis", "Reliability reviews"] },
          { icon: "observability", title: "Observability", list: ["Metrics", "Logs", "Traces", "Dashboards", "Alerting"] },
          { icon: "operations", title: "Production Operations", list: ["Incident response", "Problem management", "RCA", "Runbooks", "Operational automation"] },
          { icon: "resilience", title: "Resilience", list: ["High availability", "Disaster recovery", "Backup", "Failover", "Recovery testing"] },
        ],
      },
    ],
  },
  {
    slug: "vmware-modernization",
    navLabel: "VMware Modernization",
    title: "VMware Modernization & Virtualization Migration | FluxMigrate",
    description:
      "Assess, plan and execute your VMware exit strategy with FluxMigrate — migration to KVM, OLVM, OpenStack or cloud.",
    h1: "Plan your VMware exit **with a structured modernization path**",
    subtitle:
      "FluxMigrate helps organizations assess, plan and execute migration away from VMware to the virtualization or cloud platform that fits their environment — with minimal disruption to running workloads.",
    cta: { label: "Request a VMware Assessment", href: "/contact.html" },
    heroImage: "/images/heroes/vmware-modernization.webp",
    heroAlt: "Illustrative diagram: virtual machines moving to alternative target platforms",
    schema: { type: "Service", name: "VMware Modernization and Virtualization Migration" },
    blocks: [
      {
        type: "groups",
        title: "From assessment **to cutover**",
        columns: 3,
        items: [
          { icon: "assessment", title: "Assessment", list: ["VMware assessment", "Workload discovery", "Dependency mapping", "Application compatibility assessment"] },
          { icon: "planning", title: "Migration Planning", list: ["Migration planning", "Migration automation", "Post-migration optimization"] },
          { icon: "targets", title: "Target Platforms", list: ["VMware → KVM", "VMware → OLVM", "VMware → OpenStack", "VMware → Cloud"] },
        ],
      },
    ],
  },
  {
    slug: "staff-augmentation",
    navLabel: "Staff Augmentation",
    title: "Engineering Staff Augmentation | FluxMigrate",
    description:
      "Extend your engineering team with experienced Cloud, DevOps, Platform and SRE specialists from FluxMigrate.",
    h1: "Extend your engineering team **with Cloud, DevOps & SRE specialists**",
    subtitle:
      "Add experienced infrastructure and reliability engineers to your team without the long hiring cycle. FluxMigrate provides flexible engineering capacity for organizations that need additional expertise across cloud infrastructure, Kubernetes, DevOps automation, platform engineering and site reliability. Our engineers work alongside your existing teams, tools, repositories and operational processes.",
    cta: { label: "Request Engineering Capacity", href: "/contact.html" },
    heroImage: "/images/heroes/staff-augmentation.webp",
    heroAlt: "Illustrative diagram: specialist engineers joining an existing delivery team",
    schema: { type: "Service", name: "Engineering Staff Augmentation" },
    blocks: [
      {
        type: "groups",
        title: "Engineers **when you need them**",
        intro:
          "Whether you need one specialist or a dedicated engineering team, FluxMigrate can provide technical resources aligned with your environment and roadmap.",
        columns: 4,
        items: [
          { icon: "role-devops", title: "DevOps Engineers", list: ["CI/CD pipeline engineering", "Jenkins and Azure DevOps", "Infrastructure as Code", "Terraform & Ansible", "Docker & Kubernetes", "Release automation", "Configuration management"] },
          { icon: "role-cloud", title: "Cloud Engineers", list: ["AWS, Azure, Google Cloud", "Cloud infrastructure", "Networking and IAM", "Cloud migration", "High availability", "Disaster recovery", "Cloud cost optimization"] },
          { icon: "role-sre", title: "Site Reliability Engineers", list: ["Production reliability", "Monitoring and observability", "Incident response", "Root-cause analysis", "Capacity planning", "SLI/SLO implementation", "Operational toil reduction"] },
          { icon: "role-platform", title: "Platform Engineers", list: ["Kubernetes platforms", "OpenShift", "Internal developer platforms", "Infrastructure automation", "Platform standardization", "Developer self-service", "Container platforms"] },
        ],
      },
      {
        type: "cards",
        title: "Flexible **engagement models**",
        columns: 4,
        items: [
          { icon: "dedicated", title: "Dedicated Engineer", text: "Add an experienced engineer to your existing team for ongoing engineering capacity." },
          { icon: "pod", title: "Engineering Pod", text: "Build a small team combining Cloud, DevOps, Platform and SRE expertise." },
          { icon: "project", title: "Project-Based Engineering", text: "Bring in specialists for a defined migration, modernization or automation project." },
          { icon: "longterm", title: "Long-Term Engineering Support", text: "Maintain continuous engineering capacity for cloud infrastructure, platforms and production environments." },
        ],
      },
      {
        type: "chips",
        title: "Your environment. Your processes. **Our engineering capacity.**",
        intro: "Our engineers integrate with your existing tools rather than asking you to adopt new ones.",
        items: [
          "Git repositories", "CI/CD platforms", "Jira or Azure Boards", "Slack or Microsoft Teams",
          "AWS, Azure or GCP environments", "Kubernetes platforms", "Monitoring systems", "Incident-management processes",
        ],
        footnote:
          "The objective is simple: become an extension of your engineering organization rather than operate as a disconnected external team.",
      },
      {
        type: "cards",
        title: "Why **FluxMigrate**",
        columns: 3,
        items: [
          { icon: "why-experience", title: "Enterprise Infrastructure Experience", text: "Experience across cloud, virtualization, Kubernetes, automation and Linux infrastructure." },
          { icon: "why-scaling", title: "Flexible Scaling", text: "Increase or reduce engineering capacity according to project requirements." },
          { icon: "why-global", title: "Global Delivery", text: "Engineering resources can support distributed teams and agreed time-zone overlap." },
          { icon: "why-expertise", title: "Infrastructure Expertise", text: "Support for complex hybrid environments spanning public cloud, private cloud and on-premises infrastructure." },
          { icon: "why-security", title: "Security-Conscious Delivery", text: "Engineers operate according to client-defined access, security and operational policies." },
        ],
      },
    ],
    closing: {
      title: "Need additional **engineering capacity?**",
      text: "Tell us about your environment, technology stack and requirements.",
      cta: { label: "Request DevOps / Cloud / SRE Engineers", href: "/contact.html" },
    },
  },
  {
    slug: "technology",
    navLabel: "Technology",
    title: "Technology Expertise | FluxMigrate",
    description:
      "FluxMigrate's technology expertise across AWS, Azure, GCP, Kubernetes, OpenShift, VMware, OpenStack, Terraform, Ansible and more.",
    h1: "Technical depth **across the modern infrastructure stack**",
    subtitle:
      "From public cloud to private virtualization, automation and observability — FluxMigrate teams work across the platforms your environment already runs on.",
    cta: { label: "Talk to an Engineering Specialist", href: "/contact.html" },
    heroImage: "/images/heroes/technology.webp",
    heroAlt: "Illustrative diagram: layered infrastructure stack from cloud to observability",
    schema: { type: "CollectionPage", name: "Technology" },
    blocks: [
      {
        type: "groups",
        title: "The platforms and tools **we work with**",
        columns: 4,
        items: [
          { icon: "tech-cloud", title: "Cloud", list: ["AWS · Azure · GCP"] },
          { icon: "tech-containers", title: "Containers", list: ["Kubernetes · EKS · OpenShift · Docker"] },
          { icon: "tech-private", title: "Private Cloud", list: ["OpenStack · VMware · KVM · OLVM"] },
          { icon: "tech-automation", title: "Automation", list: ["Terraform · Ansible · Python · Bash"] },
          { icon: "tech-cicd", title: "CI/CD", list: ["Jenkins · Azure DevOps · Git"] },
          { icon: "tech-linux", title: "Linux", list: ["RHEL · Oracle Linux · SUSE · Ubuntu"] },
          { icon: "tech-observability", title: "Observability", list: ["Grafana · Prometheus · CloudWatch · Azure Monitor"] },
        ],
      },
    ],
  },
  {
    slug: "industries",
    navLabel: "Industries",
    title: "Industries | FluxMigrate",
    description:
      "FluxMigrate supports Financial Services, Telecom, SaaS and Enterprise IT with infrastructure and engineering tailored to each industry's priorities.",
    h1: "Infrastructure priorities differ by industry. **Our approach adapts.**",
    subtitle:
      "FluxMigrate works with organizations in financial services, telecom, SaaS and enterprise IT — each with distinct reliability, security and scale requirements.",
    cta: { label: "Talk to an Engineering Specialist", href: "/contact.html" },
    heroImage: "/images/heroes/industries.webp",
    heroAlt: "Illustrative diagram: four industry areas served by one engineering approach",
    schema: { type: "CollectionPage", name: "Industries" },
    blocks: [
      {
        type: "tabs",
        title: "What matters **in your industry**",
        tabs: [
          { id: "financial", label: "Financial Services", icon: "ind-finance", items: ["Security", "High availability", "Disaster recovery", "Hybrid infrastructure", "Regulatory requirements", "Production reliability"] },
          { id: "telecom", label: "Telecom", icon: "ind-telecom", items: ["Large-scale infrastructure", "Kubernetes", "OpenStack", "NFV", "Automation", "High availability", "24/7 operations"] },
          { id: "saas", label: "SaaS & Technology", icon: "ind-saas", items: ["Kubernetes", "CI/CD", "Platform engineering", "Cloud optimization", "SRE", "Developer productivity"] },
          { id: "enterprise", label: "Enterprise IT", icon: "ind-enterprise", items: ["Data-center modernization", "Cloud migration", "VMware modernization", "Hybrid cloud", "Infrastructure automation"] },
        ],
      },
    ],
  },
  {
    slug: "about",
    navLabel: "About",
    title: "About | FluxMigrate",
    description:
      "FluxMigrate is a cloud infrastructure, DevOps and reliability engineering company supporting the complete infrastructure lifecycle.",
    h1: "Engineers who build **and operate the infrastructure they design**",
    subtitle:
      "FluxMigrate helps enterprises design, migrate, automate and operate modern cloud and hybrid infrastructure — while providing experienced Cloud, DevOps, Platform and SRE engineers to extend their teams.",
    cta: { label: "Talk to an Engineering Specialist", href: "/contact.html" },
    heroImage: "/images/heroes/about.webp",
    heroAlt: "Illustrative diagram: design, build and operate as one continuous loop",
    schema: { type: "AboutPage", name: "About" },
    blocks: [
      {
        type: "cards",
        title: "How we **think about the work**",
        columns: 3,
        items: [
          { icon: "about-what", title: "What we do", text: "Cloud architecture, migration, DevOps automation and site reliability engineering, delivered as projects or as ongoing engineering capacity." },
          { icon: "about-how", title: "How we work", text: "Our engineers integrate with your existing tools, repositories and processes rather than asking you to adopt new ones." },
          { icon: "about-where", title: "Where we focus", text: "Public cloud, private virtualization, Kubernetes/OpenShift platforms, and the automation and reliability practices that keep them running." },
        ],
      },
    ],
  },
];

export const contactPage = {
  slug: "contact",
  title: "Contact | FluxMigrate",
  description:
    "Request a cloud infrastructure project or DevOps, Cloud and SRE engineering capacity from FluxMigrate.",
  h1: "Tell us about your environment **and requirements**",
  subtitle:
    "Whether you need a defined infrastructure project or ongoing engineering capacity, tell us what you're working with and we'll follow up.",
  heroImage: "/images/heroes/contact.webp",
  heroAlt: "Illustrative diagram: a request reaching an engineering team",
  needs: ["Cloud Migration", "DevOps", "Kubernetes / OpenShift", "SRE", "Infrastructure Operations", "VMware Modernization", "Staff Augmentation", "Other"],
  engineers: ["1", "2–3", "4–6", "7+"],
  engagements: ["Project", "Short-term", "Long-term", "Not sure"],
};

export const notFound = {
  title: "Page not found | FluxMigrate",
  links: [
    { title: "Services", items: [
      { name: "Cloud & Migration", href: "/cloud-migration.html" },
      { name: "DevOps & Platform", href: "/devops-platform-engineering.html" },
      { name: "SRE & Reliability", href: "/sre-reliability-engineering.html" },
      { name: "VMware Modernization", href: "/vmware-modernization.html" },
    ] },
    { title: "Company", items: [
      { name: "Staff Augmentation", href: "/staff-augmentation.html" },
      { name: "Technology", href: "/technology.html" },
      { name: "Industries", href: "/industries.html" },
      { name: "About", href: "/about.html" },
    ] },
    { title: "Get started", items: [
      { name: "Plan a project", href: "/contact.html" },
      { name: "Request engineers", href: "/staff-augmentation.html" },
      { name: "Book a discovery call", href: "/contact.html" },
    ] },
  ],
};
